# Generated by Django 2.0.6 on 2018-06-29 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcludedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stavpoisk_id', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Monitor', verbose_name='Monitor')),
            ],
        ),
        migrations.AddField(
            model_name='excludeduser',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Monitor', verbose_name='Monitor'),
        ),
        migrations.AddField(
            model_name='cachedhtml',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Monitor', verbose_name='Monitor'),
        ),
    ]
